In [2]:
# list 
my_list = [1, 2, 3, 4, 5]

# tuple
my_tuple = (1, 2, 3, 4, 5)

# set 
my_set = {1, 2, 3, 4, 5}

## Dictionary

In [3]:
# TH to EN
# ข้าว - rice

my_dict = {'ข้าว': 'rice'}
print(type(my_dict))

<class 'dict'>


In [4]:
my_dict.keys()

dict_keys(['ข้าว'])

In [5]:
my_dict.values()

dict_values(['rice'])

In [6]:
my_dict.items()

dict_items([('ข้าว', 'rice')])

In [7]:
my_dict['ข้าว']

'rice'

In [8]:
my_dict['rice']

KeyError: 'rice'

In [ ]:
translator = {
    'ข้าว' : 'rice',
    'ปลา' : 'fish',
    'ผลไม้' : 'fruit',
    'หมู' : 'pork',
    'น้ำ' : 'water'
}

print(translator)

{'ข้าว': 'rice', 'ปลา': 'fish', 'ผลไม้': 'fruit', 'หมู': 'pork', 'น้ำ': 'water'}


In [2]:
translator_2 = {
    'ผู้ชาย': 'male',
    'สิงโต' : 'lion', 
    'หมู': 'pig',
    'แท่งหรรษา': 'joystick',
    'เต้าหู้': 'tofu',
    'แมว':'cat',
    'กัญชา': 'weed'
}

In [ ]:
print(translator['น้ำ'])
print(translator_2['น้ำ'])

water


KeyError: 'น้ำ'

In [ ]:
def get_en_translation(thai_word, word_dict=translator_2):
    #### statement
    english_word = word_dict[thai_word]
    return english_word

In [ ]:
#print(get_en_translation('ผลไม้', translator_2))
print('Words in Translater 1: ', get_en_translation('หมู', translator))
print('Words in Translater 2: ', get_en_translation('หมู'))
print('Words in Translater 2: ', get_en_translation(thai_word='หมู', word_dict=translator))
print('Words in Translater 2: ', get_en_translation(word_dict=translator, thai_word='หมู'))

Words in Translater 1:  pork
Words in Translater 2:  pig
Words in Translater 2:  pork
Words in Translater 2:  pork


In [ ]:
# print key by iterations
for w in translator_2:
    print(w)

ผู้ชาย
สิงโต
หมู
แท่งหรรษา
เต้าหู้
แมว
กัญชา


In [5]:
# print key by iterations
for w in translator_2.keys():
    print(w)

ผู้ชาย
สิงโต
หมู
แท่งหรรษา
เต้าหู้
แมว
กัญชา


In [ ]:
# print values by iterations
for w in translator_2.values():
    print(w)

male
lion
pig
joystick
tofu
cat
weed


In [ ]:
# print items by iterations
for w in translator_2.items():
    #print(w)
    print(w[0])

ผู้ชาย
สิงโต
หมู
แท่งหรรษา
เต้าหู้
แมว
กัญชา


In [ ]:
translator_3 = translator_2.copy()
translator_3

{'ผู้ชาย': 'male',
 'สิงโต': 'lion',
 'หมู': 'pig',
 'แท่งหรรษา': 'joystick',
 'เต้าหู้': 'tofu',
 'แมว': 'cat',
 'กัญชา': 'weed'}

In [ ]:
translator_3['male'] = 'ผู้ชาย'
translator_3

{'ผู้ชาย': 'male',
 'สิงโต': 'lion',
 'หมู': 'pig',
 'แท่งหรรษา': 'joystick',
 'เต้าหู้': 'tofu',
 'แมว': 'cat',
 'กัญชา': 'weed',
 'male': 'ผู้ชาย'}

In [ ]:
en_th_dict = dict()
en_th_dict

{}

In [ ]:
# alternative I 
def get_en_dict(old_dict):
    en_th_dict = dict()
    for key in old_dict:
        en_th_dict[old_dict[key]] = key
    return en_th_dict

In [ ]:
new_dict = get_en_dict(old_dict=translator_2)
new_dict

{'male': 'ผู้ชาย',
 'lion': 'สิงโต',
 'pig': 'หมู',
 'joystick': 'แท่งหรรษา',
 'tofu': 'เต้าหู้',
 'cat': 'แมว',
 'weed': 'กัญชา'}

In [ ]:
rdm_dict = {
    'key1': [1, 2, 3, 4 ,5],
    'key2': [4.5, 2.3, 2.6],
    'key3': 'this is the third value in this dictionary',
    'key4': {'key41': None, 
             'key42': [9, 7 ,8]}
}

rdm_dict 

{'key1': [1, 2, 3, 4, 5],
 'key2': [4.5, 2.3, 2.6],
 'key3': 'this is the third value in this dictionary',
 'key4': {'key41': None, 'key42': [9, 7, 8]}}

In [6]:
# check data type
isinstance('A', str)

True

In [ ]:
for dict in rdm_dict:
    #if type(rdm_dict[dict]) == str:
    if isinstance(rdm_dict[dict], str):
        rdm_dict[dict] = rdm_dict[dict].split(" ")
    for value in rdm_dict[dict]:
        print(value)

1
2
3
4
5
4.5
2.3
2.6
this
is
the
third
value
in
this
dictionary
key41
key42


In [ ]:
for k in rdm_dict:
    for m in rdm_dict[k]:
        print(m)

1
2
3
4
5
4.5
2.3
2.6
t
h
i
s
 
i
s
 
t
h
e
 
t
h
i
r
d
 
v
a
l
u
e
 
i
n
 
t
h
i
s
 
d
i
c
t
i
o
n
a
r
y
key41
key42


In [ ]:
json = {"menu": {
        "id": "file",
        "value": "File",
        "popup": {
            "menuitem": [
              {"value": "New", "onclick": "CreateNewDoc()"},
              {"value": "Open", "onclick": "OpenDoc()"},
              {"value": "Close", "onclick": "CloseDoc()"}
    ]
  }
}}

json

{'menu': {'id': 'file',
  'value': 'File',
  'popup': {'menuitem': [{'value': 'New', 'onclick': 'CreateNewDoc()'},
    {'value': 'Open', 'onclick': 'OpenDoc()'},
    {'value': 'Close', 'onclick': 'CloseDoc()'}]}}}

In [ ]:
print(json)

{'menu': {'id': 'file', 'value': 'File', 'popup': {'menuitem': [{'value': 'New', 'onclick': 'CreateNewDoc()'}, {'value': 'Open', 'onclick': 'OpenDoc()'}, {'value': 'Close', 'onclick': 'CloseDoc()'}]}}}


In [ ]:
json['menu']['popup']['menuitem'][0]['onclick']

'CreateNewDoc()'

In [ ]:
# list comprehension
list0 = [i for i in range(0,1000)]
list0[0], list0[-1]

(0, 999)

In [ ]:
0
1000
2000
.
.
.
999000

In [ ]:
list1 = [i*1000 for i in range(0,1000)]
list1

list

In [ ]:
my_new_list = []
for i in list0:
        my_new_list.append(i*1000)
        
my_new_list

[0,
 1000,
 2000,
 3000,
 4000,
 5000,
 6000,
 7000,
 8000,
 9000,
 10000,
 11000,
 12000,
 13000,
 14000,
 15000,
 16000,
 17000,
 18000,
 19000,
 20000,
 21000,
 22000,
 23000,
 24000,
 25000,
 26000,
 27000,
 28000,
 29000,
 30000,
 31000,
 32000,
 33000,
 34000,
 35000,
 36000,
 37000,
 38000,
 39000,
 40000,
 41000,
 42000,
 43000,
 44000,
 45000,
 46000,
 47000,
 48000,
 49000,
 50000,
 51000,
 52000,
 53000,
 54000,
 55000,
 56000,
 57000,
 58000,
 59000,
 60000,
 61000,
 62000,
 63000,
 64000,
 65000,
 66000,
 67000,
 68000,
 69000,
 70000,
 71000,
 72000,
 73000,
 74000,
 75000,
 76000,
 77000,
 78000,
 79000,
 80000,
 81000,
 82000,
 83000,
 84000,
 85000,
 86000,
 87000,
 88000,
 89000,
 90000,
 91000,
 92000,
 93000,
 94000,
 95000,
 96000,
 97000,
 98000,
 99000,
 100000,
 101000,
 102000,
 103000,
 104000,
 105000,
 106000,
 107000,
 108000,
 109000,
 110000,
 111000,
 112000,
 113000,
 114000,
 115000,
 116000,
 117000,
 118000,
 119000,
 120000,
 121000,
 122000,
 12300

In [ ]:
array(my_new_list)

NameError: name 'array' is not defined

In [ ]:
!pip install numpy

In [ ]:
import numpy as np 
arr1 = numpy.array(my_new_list)
arr1

NameError: name 'numpy' is not defined

In [8]:
import numpy as np

In [ ]:
numbers = np.arange(0, 10)
numbers 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10, 101, 10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [9]:
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

In [ ]:
print(np.linspace(10,100,10))
print(np.arange(10, 101, 10))

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
np.linspace(10,100,10) == np.arange(10, 101, 10)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
np.random.randint(0, 10, 10)

array([2, 5, 7, 8, 4, 9, 2, 0, 1, 8])

In [ ]:
# 1 d to 2 d array
np.random.randint(0, 10, 10).reshape(1, -1)

array([[0, 6, 3, 1, 8, 7, 5, 4, 3, 6]])

In [ ]:
np.random.randint(0, 10, 9).reshape(3, 3, 1)

array([[[5],
        [1],
        [3]],

       [[9],
        [9],
        [2]],

       [[5],
        [1],
        [2]]])

In [ ]:
np.random.randint(0, 10, 10).shape

(10,)

#### 2D Array

In [13]:
_2d_array = np.array([[1, 2, 3, 4, 5],
                      [6, 7, 8, 9, 10]])
_2d_array.shape

(2, 5)

In [14]:
_2d_array.reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
_2d_array[1][-1]

10

In [19]:
_2d_array[1]

array([ 6,  7,  8,  9, 10])

In [21]:
np.array([
    np.random.randint(0, 10, 10),
    np.linspace(10,100,10)
])

array([[  8.,   5.,   8.,   5.,   9.,   6.,   9.,   5.,   8.,   2.],
       [ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]])

In [ ]:
elevens = np.array([11, 22, 33, 44 ,55 ,66 ,77, 88, 99])
elevens/11

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

Buld an array that contains 
first row is the number array ranged from 11 to 99, increment = 11
second row is the first 9 english alphabhets
third row is the the results of first row/11

In [ ]:
np.arange(11, 100, 11)

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [23]:
np.linspace(11, 99, 9)

array([11., 22., 33., 44., 55., 66., 77., 88., 99.])

In [26]:
results = np.array([
    np.arange(11, 100, 11), 
    np.array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']),
    np.arange(11, 100, 11)/11
])

results

array([['11', '22', '33', '44', '55', '66', '77', '88', '99'],
       ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
       ['1.0', '2.0', '3.0', '4.0', '5.0', '6.0', '7.0', '8.0', '9.0']],
      dtype='<U32')

In [ ]:
results[1][2]

'C'

In [27]:
results[1].str.lower()

AttributeError: 'numpy.ndarray' object has no attribute 'str'

In [28]:
results[1] = [char.lower() for char in results[1]]
results[1] 

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='<U32')

In [ ]:
print(np.sctypes)

{'int': [<class 'numpy.int8'>, <class 'numpy.int16'>, <class 'numpy.int32'>, <class 'numpy.int64'>], 'uint': [<class 'numpy.uint8'>, <class 'numpy.uint16'>, <class 'numpy.uint32'>, <class 'numpy.uint64'>], 'float': [<class 'numpy.float16'>, <class 'numpy.float32'>, <class 'numpy.float64'>, <class 'numpy.float128'>], 'complex': [<class 'numpy.complex64'>, <class 'numpy.complex128'>, <class 'numpy.complex256'>], 'others': [<class 'bool'>, <class 'object'>, <class 'bytes'>, <class 'str'>, <class 'numpy.void'>]}


In [ ]:
np.linspace(11, 99, 9)

array([11., 22., 33., 44., 55., 66., 77., 88., 99.])

In [ ]:
np.mean(np.linspace(11, 99, 9))

55.0

In [ ]:
np.std(np.linspace(11, 99, 9))

28.401877872187722

In [ ]:
np.max(np.linspace(11, 99, 9))

99.0

In [ ]:
np.min(np.linspace(11, 99, 9))

11.0

In [ ]:
# function
# input array
# print mean, sd 
# output z-score array

def calculate_z_score(array):
    mean = np.mean(array)
    std = np.std(array)
    z_score = (array-mean)/std
    print(mean) 
    print(std)
    return z_score

calculate_z_score(array=np.linspace(11, 99, 9))

55.0
28.401877872187722


array([-1.54919334, -1.161895  , -0.77459667, -0.38729833,  0.        ,
        0.38729833,  0.77459667,  1.161895  ,  1.54919334])

In [ ]:
a = np.linspace(11, 99, 9).reshape(-1, 1)
b = np.arange(11, 100, 11).reshape(-1, 1)

In [ ]:
print(a)
print(b)

[[11.]
 [22.]
 [33.]
 [44.]
 [55.]
 [66.]
 [77.]
 [88.]
 [99.]]
[[11]
 [22]
 [33]
 [44]
 [55]
 [66]
 [77]
 [88]
 [99]]


In [ ]:
np.concatenate((a, b), axis=0)

array([[11.],
       [22.],
       [33.],
       [44.],
       [55.],
       [66.],
       [77.],
       [88.],
       [99.],
       [11.],
       [22.],
       [33.],
       [44.],
       [55.],
       [66.],
       [77.],
       [88.],
       [99.]])

In [ ]:
np.vstack((a,b))

array([[11.],
       [22.],
       [33.],
       [44.],
       [55.],
       [66.],
       [77.],
       [88.],
       [99.],
       [11.],
       [22.],
       [33.],
       [44.],
       [55.],
       [66.],
       [77.],
       [88.],
       [99.]])

In [ ]:
np.vstack((a,b)).reshape(9, 2)

array([[11., 22.],
       [33., 44.],
       [55., 66.],
       [77., 88.],
       [99., 11.],
       [22., 33.],
       [44., 55.],
       [66., 77.],
       [88., 99.]])

In [ ]:
np.hstack((a,b))

array([[11., 11.],
       [22., 22.],
       [33., 33.],
       [44., 44.],
       [55., 55.],
       [66., 66.],
       [77., 77.],
       [88., 88.],
       [99., 99.]])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
zeroones = np.random.randint(0, 2, 10)
zeroones 

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 1])

In [ ]:
ones_check = np.where(zeroones==1, True, False)
ones_check

array([False, False, False,  True,  True, False,  True,  True, False,
        True])

In [2]:
import numpy as np

In [25]:
a1 = [1, 2, 3, 4 ,5] ## take this
mult = 10 ## take this 
a2 = [i*mult for i in a1]
a3 = [True, True, True, True, True]

result = []
for i in range(len(a1)):
    result.append([a1[i], a2[i], a3[i]])

result
A = np.vstack((result)).reshape(5,3)
A

[True, True, True, True, True]


array([[ 1, 10,  1],
       [ 2, 20,  1],
       [ 3, 30,  1],
       [ 4, 40,  1],
       [ 5, 50,  1]])

In [ ]:
[1, 10., True]
[2, 20., True]
.
.
.
[5, 50., True]